name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: axeloooo
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker build and Push
        run: |
          docker build -t Axeloooo/portfolio .
          docker push Axeloooo/portfolio
